[
    {
        "predicted_code": "# generated by https://github.com/cphaff/cadtuna\nimport cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.015625, 0.0, -0.75), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.015, 0.0).lineTo(0.015, 0.012463815789473684).lineTo(0.0, 0.0124638157894736",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.015625, -0.0078125, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.0, 0.0).threePointArc((0.0007948582418457166, -0.0019189575476279677), (0.0027138157894736844, -0.0027138157894736844)).lineTo(0.021217105263157895, -0.0027138157894736844).threePointArc((0.022787161438489866, -0.00206347722796355), (0.0234375, -0.000493421052631579)).lineTo(0.0234375, 0.018256578947368422).threePointArc((0.02283825686147997, 0.019949990385858287), (0.021217105263157895, 0.020723684210526318)).lineTo(0.0022203947368421052, 0.020723684210526318).threePointArc((0.0005992431385200307, 0.019949990385858287), (0.0, 0.018256578947368422)).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.75)\nsolid=solid0\n"
    },
    {
        "predicted_code": "# generated by caffe2.pythontools.generator\nimport cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.546875, -0.578125, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.0, 0.0).threePointArc((0.0796875, -0.38362889999999997), (0.4137171052631579, -0.578125)).lineTo(0.5625, -0.578125).lineTo(0.7046875, -0.35394736842105265).threePointArc((0.78023947",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, -0.1953125, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.17730263157894738, 0.0).lineTo(0.17730263157894738, 0.38281250000000006).lineTo(0.0, 0.38281250000000006).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.3046875)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(0.1796875, -0.109375, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop1=wp_sketch1.moveTo(0.3782072368421052, 0.0).lineTo(0.5703125, 0.1140625).lineTo(0.3782072368421052, 0.22212171052631577).lineTo(0.0, 0.22212171052631577).lineTo(0.0, 0.0).close()\nsolid1=wp_sketch1.add(loop1).extrude(0.1796875)\nsolid=solid.union(solid1)\n"
    },
    {
        "predicted_code": "# generated by https://github.com/cadquery/cadquery-anki\nimport cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.140625, -0.03125, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.14144736842105263, 0.0).threePointArc((0.21209375, -0.03125), (0.2734375, 0.0)).lineTo(0.3046875, 0.03125).lineTo(0.3046875, 0.34375).lineTo(0.14144736842105263, 0.343",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.1015625, 0.0, -0.046875), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.0, 0.0).threePointArc((0.0019490941863378162, -0.04433658679437616), (0.03355263157894737, -0.07549342105263158)).threePointArc((0.09646381578947369, -0.08720656501962193), (0.159375, -0.07549342105263158)).threePointArc((0.19097853739260956, -0.044336586794376284), (0.19292763157894738, 0.0)).lineTo(0.14259868421052632, 0.18453947368421053).lineTo(0.14259868421052632, 0.796875).lineTo(0.10904605263157895, 0.796875).lineTo(0.10904605263157895, 0.7381578947368421).lineTo(0.08388157894736842, 0.7381578947368421).lineTo(0.08388157894736842, 0.796875).lineTo(0.0587171052631579, 0.796875).lineTo(0.0587171052631579, 0.18453947368421053).lineTo(0.0, 0.0).close()\nloop1=wp_sketch0.moveTo(0.0, 0.0).threePointArc((0.0725867756556451, -0.03002210922402418), (0.15098684210526317, -0.025164473684210528)).lineTo(0.10904605263157895, 0.10904605263157895).lineTo(0.08388157894736842, 0.10904605263157895).lineTo(0.04194078947368421, -0.025164473684210528).close()\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.0234375)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, -0.375), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(1.5, 0.0).lineTo(1.5, 0.75).lineTo(0.0, 0.75).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.375)\nsolid=solid0",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.0, 0.0), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.296875, 0.0).lineTo(0.296875, 0.296875).lineTo(0.0, 0.296875).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.75)\nsolid=solid0\n"
    },
    {
        "predicted_code": "# generated by caffe2.pythontools.create_caffe2_query(caffe2_query)\nimport cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.0, 0.0), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.75, 0.0).lineTo(0.75, 0.38684210526315794).lineTo(0.2973684210526316, 0.386",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.0, -0.3515625), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.19736842105263158, 0.0).lineTo(0.2368421052631579, 0.0).lineTo(0.35526315789473684, 0.0).lineTo(0.39473684210526316, 0.0).lineTo(0.5131578947368421, 0.0).lineTo(0.5526315789473685, 0.0).lineTo(0.75, 0.0).lineTo(0.75, 0.35526315789473684).lineTo(0.5131578947368421, 0.35526315789473684).lineTo(0.2368421052631579, 0.35526315789473684).lineTo(0.0, 0.35526315789473684).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.125, both=True)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.234375, 0.0), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\nloop1=wp_sketch1.moveTo(0.28125, 0.0).lineTo(0.28125, 0.12434210526315789).lineTo(0.0, 0.12434210526315789).lineTo(0.0, 0.0).close()\nsolid1=wp_sketch1.add(loop1).extrude(0.0625, both=True)\nsolid=solid.union(solid1)\n# Generating a workplane for sketch 2\nwp_sketch2 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.203125, -0.6484375), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\nloop2=wp_sketch2.moveTo(0.037500000000000006, 0.0).lineTo(0.037500000000000006, 0.296875).lineTo(0.0, 0.296875).lineTo(0.0, 0.0).close()\nsolid2=wp_sketch2.add(loop2).extrude(0.015625, both=True)\nsolid=solid.union(solid2)\n# Generating a workplane for sketch 3\nwp_sketch3 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.359375, -0.6484375), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\nloop3=wp_sketch3.moveTo(0.037500000000000006, 0.0).lineTo(0.037500000000000006, 0.296875).lineTo(0.0, 0.296875).lineTo(0.0, 0.0).close()\nsolid3=wp_sketch3.add(loop3).extrude(0.015625, both=True)\nsolid=solid.union(solid3)\n# Generating a workplane for sketch 4\nwp_sketch4 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.515625, -0.6484375), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\nloop4=wp_sketch4.moveTo(0.037500000000000006, 0.0).lineTo(0.037500000000000006, 0.296875).lineTo(0.0, 0.296875).lineTo(0.0, 0.0).close()\nsolid4=wp_sketch4.add(loop4).extrude(0.015625, both=True)\nsolid=solid.union(solid4)\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.2734375, 0.0, 0.0), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.0, 0.0).lineTo(0.0, 0.048684210526315784).lineTo(0.0, 0.09736842105263157).lineTo(0.023447368421052",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, -0.0390625, -0.15625), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.0352796052631579, 0.0).threePointArc((0.03754746418308187, 0.0009393779221812848), (0.03848684210526316, 0.003207236842105263)).lineTo(0.03848684210526316, 0.3014802631578947).threePointArc((0.03754746418308187, 0.3037481220778187), (0.0352796052631579, 0.3046875)).lineTo(0.0, 0.3046875).lineTo(0.0, 0.29827302631578945).lineTo(0.032072368421052634, 0.29827302631578945).lineTo(0.032072368421052634, 0.006414473684210526).lineTo(0.0, 0.006414473684210526).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.75, both=True)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(0.75, 0.0, 0.125), cq.Vector(-1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, 1.0, 6.123233995736766e-17)))\nloop1=wp_sketch1.moveTo(0.011842105263157895, 0.0).circle(0.011842105263157895)\nsolid1=wp_sketch1.add(loop1).extrude(-0.0234375)\nsolid=solid.cut(solid1)\n# Generating a workplane for sketch 2\nwp_sketch2 = cq.Workplane(cq.Plane(cq.Vector(0.75, 0.0, -0.125), cq.Vector(-1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, 1.0, 6.123233995736766e-17)))\nloop2=wp_sketch2.moveTo(0.011842105263157895, 0.0).circle(0.011842105263157895)\nsolid2=wp_sketch2.add(loop2).extrude(-0.0234375)\nsolid=solid.cut(solid2)\n# Generating a workplane for sketch 3\nwp_sketch3 = cq.Workplane(cq.Plane(cq.Vector(-0.7265625, 0.0, 0.125), cq.Vector(-1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, 1.0, 6.123233995736766e-17)))\nloop3=wp_sketch3.moveTo(0.011842105263157895, 0.0).circle(0.011842105263157895)\nsolid3=wp_sketch3.add(loop3).extrude(-0.0234375)\nsolid=solid.cut(solid3)\n# Generating a workplane for sketch 4\nwp_sketch4 = cq.Workplane(cq.Plane(cq.Vector(-0.7265625, 0.0, -0.125), cq.Vector(-1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, 1.0, 6.123233995736766e-17)))\nloop4=wp_sketch4.moveTo(0.011842105263157895, 0.0).circle(0.011842105263157895)\nsolid4=wp_sketch4.add(loop4).extrude(-0.0234375)\nsolid=solid.cut(solid4)\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.3359375, -0.75, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.02368421052631579, 0.0).lineTo(0.02368421052631579, 1.5).lineTo(1.5, 1.5).lineTo(1.5, 0.0).lineTo(1.5236842105263157, 0.02368421052631579).lineTo(1.5236842105263157, 1.47631578947368",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.6640625, -0.75, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(1.3263157894736843, 0.0).lineTo(1.3263157894736843, 1.5).lineTo(0.0, 1.5).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.0234375)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, -0.46875, -0.3984375), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.9210526315789473, 0.0).lineTo(0.9210526315789473, 0.870921052631579).lineTo(0.0, 0.870921052631579).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(-0.1015625)\nsolid=solid0",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, -0.75, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.6789473684210526, 0.0).lineTo(0.6789473684210526, 0.75).lineTo(0.0, 0.75).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.0390625)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, -0.3359375), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.8609375, 0.0).lineTo(0.8609375, 0.44342105263157895).lineTo(0.0, 0.44342105263157895).lineTo(0.0,",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.3359375, -0.75, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.6631578947368422, 0.0).lineTo(0.6631578947368422, 1.5).lineTo(0.0, 1.5).lineTo(0.0, 0.0).close()\nloop1=wp_sketch0.moveTo(0.6157894736842106, 0.06315789473684211).lineTo(0.6157894736842106, 1.436842105263158).lineTo(0.06315789473684211, 1.436842105263158).lineTo(0.06315789473684211, 0.06315789473684211).close()\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.0390625)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.3359375, 0.0, -0.0625), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.7421875, 0.0).lineTo(0.7421875, 0.12467105263157895).lineTo(0.0, 0.12467105263157895).lineTo(0.0",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.7109375, 0.0, -0.296875), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(1.4296875, 0.0).lineTo(1.4296875, 0.6019736842105263).lineTo(0.0, 0.6019736842105263).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(-0.0546875)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.703125, 0.0, -0.3046875), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(1.4140625, 0.0).lineTo(1.4140625, 0.6421052631578948).lineTo(0.0, 0.6421052631578948).lineTo(0.0",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.5, -0.75, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.9947368421052631, 0.0).lineTo(0.9947368421052631, 1.5).lineTo(0.0, 1.5).lineTo(0.0, 0.0).close()\nloop1=wp_sketch0.moveTo(0.7894736842105263, 0.2210526315789474).lineTo(0.7894736842105263, 1.2789473684210526).lineTo(0.2210526315789474, 1.2789473684210526).lineTo(0.2210526315789474, 0.2210526315789474).close()\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.21875)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, -0.5234375), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.078125, 0.0).lineTo(0.078125, 0.868421052631579).lineTo(1.6015625, 0.868421052631579).lineTo(1.601",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.0, 0.0), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.75, 0.0).lineTo(0.75, 0.41842105263157897).lineTo(0.0, 0.41842105263157897).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.015625)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.5703125, 0.0, 0.0), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.5997118421052632, 0.0).lineTo(0.5997118421052632, 0.41429503289473686).lineTo(0.4871710526315",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.375, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.18947368421052632, -0.3236842105263158).lineTo(0.5605263157894737, -0.3236842105263158).lineTo(0.75, 0.0).lineTo(0.5605263157894737, 0.3236842105263158).lineTo(0.18947368421052632, 0.3236842105263158).lineTo(0.0, 0.0).close()\nloop1=wp_sketch0.moveTo(0.20526315789473684, -0.3).lineTo(0.5447368421052632, -0.3).lineTo(0.718421052631579, 0.0).lineTo(0.5447368421052632, 0.3).lineTo(0.20526315789473684, 0.3).lineTo(0.031578947368421054, 0.0).close()\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.75)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, -0.2421875, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.75, -0.2421875).lineTo(0.75, 0.0).lineTo(1.5, 0.0).lineTo(1.5, 0.2421875).lineTo(1.5, 0.36636842105263158).lineTo(1.25, 0.36636842105263158).lineTo(1.25, 0.48486842105263157).lineTo(0.75, 0.48486",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, -0.3046875), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(1.5, 0.0).lineTo(1.5, 0.06315789473684211).lineTo(1.405263157894737, 0.06315789473684211).threePointArc((1.3350039873425394, 0.09880041020337962), (1.3105263157894738, 0.1736842105263158)).lineTo(1.3105263157894738, 0.3157894736842105).lineTo(0.18947368421052632, 0.3157894736842105).lineTo(0.18947368421052632, 0.1736842105263158).threePointArc((0.1649960126574607, 0.09880041020337962), (0.09473684210526316, 0.06315789473684211)).lineTo(0.0, 0.06315789473684211).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.3359375)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, 0.203125), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop1=wp_sketch1.moveTo(0.19802631578947366, -0.19802631578947366).lineTo(0.19802631578947366, 0.21874999999999997).lineTo(0.1796052631578947, 0.21874999999999997).lineTo(0.0, 0.03914473684210526).lineTo(0.0, 0.0).close()\nsolid1=wp_sketch1.add(loop1).extrude(0.3359375)\nsolid=solid.union(solid1)\n# Generating a workplane for sketch 2\nwp_sketch2 = cq.Workplane(cq.Plane(cq.Vector(0.5546875, 0.0, 0.0078125), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop2=wp_sketch2.moveTo(0.19613486842105263, 0.19613486842105263).lineTo(0.19613486842105263, 0.23536184210526315).lineTo(0.017434210526315788, 0.41406249999999994).lineTo(0.0, 0.41406249999999994).lineTo(0.0, 0.0).close()\nsolid2=wp_sketch2.add(loop2).extrude(0.3359375)\nsolid=solid.union(solid2)\n# Generating a workplane for sketch 3\nwp_sketch3 = cq.Workplane(cq.Plane(cq.Vector(-0.5546875, 0.0, 0.0078125), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop3=wp_sketch3.moveTo(1.109375, 0.0).lineTo(1.109375, 0.4087171052631579).lineTo(0.0, 0.4087171052631579).lineTo(0.0, 0.0).close()\nsolid3=wp_sketch3.add(loop3).extrude(0.3359375)\nsolid=solid.union(solid3)\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.546875, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.5526315789473684, 0.0).circle(0.5526315789473684)\nsolid0=wp_sketch0.add(loop0).extrude(0.078125)\nsolid=solid0",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.7578947368421053)\nsolid0=wp_sketch0.add(loop0).extrude(0.1484375)\nsolid=solid0\n"
    },
    {
        "predicted_code": "# generated by caffe2.python.generate_caffe2_code\nimport caffe2.python\nimport caffe2.proto\nimport core\nimport geometry\nimport math\nimport sys\nimport six\nimport weakref\nimport threading\n\nimport pdb\nimport caffe2.python.six as six\nimport sys\nimport io\n\nimport copy\nimport random\nimport math\nimport caffe2.python.gpu_wrap\nimport threading\nimport pdb\nimport copy\nimport random\nimport math\nimport caffe2.python.gpu_wrap\nimport threading\nimport pdb\nimport copy\nimport random\nimport math\nimport caffe2.python.gpu_wrap\nimport threading\nimport pdb\nimport copy\nimport random\nimport math\nimport caffe2.python.gpu_wrap\nimport threading\nimport pdb\nimport copy\nimport random\nimport math\nimport caffe2.python.gpu_wrap\nimport threading\nimport pdb\nimport copy\nimport random\nimport math\nimport caffe2.python.gpu_wrap\nimport threading\nimport pdb\nimport copy\nimport random\nimport math\nimport caffe2.python.gpu_wrap\nimport threading\nimport pdb\nimport copy\nimport random\nimport math\nimport caffe2",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.28125, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.28421052631578947, 0.0).circle(0.28421052631578947)\nsolid0=wp_sketch0.add(loop0).extrude(0.75)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(-0.109375, 0.0, 0.75), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop1=wp_sketch1.moveTo(0.11052631578947367, 0.0).circle(0.11052631578947367)\nsolid1=wp_sketch1.add(loop1).extrude(-0.328125)\nsolid=solid.cut(solid1)\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.0390625, 0.0, -0.75), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.039473684210526314, 0.0).lineTo(0.039473684210526314, 0.008823366111842106).lineTo(0.0, 0.00",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.0, 0.0078125), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.0029605263157894738, 0.0).lineTo(0.0029605263157894738, 0.01644736842105263).lineTo(0.028289473684210524, 0.01644736842105263).lineTo(0.028289473684210524, 0.0).lineTo(0.03125, 0.0).lineTo(0.03125, 0.019407894736842103).lineTo(0.0, 0.019407894736842103).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(-0.75)\nsolid=solid0\n"
    },
    {
        "predicted_code": "# generated by https://github.com/cadquery/cadquery\nimport cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.1875, 0.0, 0.0), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.09023026315789474, 0.0).lineTo(0.09023026315789474, 0.15000000000000002).lineTo(0",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, -0.515625, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(1.5, 0.0).lineTo(1.5, 1.0263157894736843).lineTo(0.0, 1.0263157894736843).lineTo(0.0, 0.0).close()\nloop1=wp_sketch0.moveTo(0.3157894736842105, 0.26842105263157895).circle(0.04736842105263158)\nloop2=wp_sketch0.moveTo(0.3157894736842105, 0.7578947368421053).circle(0.04736842105263158)\nloop3=wp_sketch0.moveTo(1.1842105263157896, 0.26842105263157895).circle(0.04736842105263158)\nloop4=wp_sketch0.moveTo(1.1842105263157896, 0.7578947368421053).circle(0.04736842105263158)\nsolid0=wp_sketch0.add(loop0).add(loop1).add(loop2).add(loop3).add(loop4).extrude(0.0859375)\nsolid=solid0\n"
    },
    {
        "predicted_code": "# generated by caffe2.python.\nimport cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.015625, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.02271144736842105, 0.0).circle(0.02271144736842105)\nsolid0=wp_sketch0.add(loop0).extrude(-0.75)\nsolid=solid0",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.0390625, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.039473684210526314, 0.0).circle(0.039473684210526314)\nsolid0=wp_sketch0.add(loop0).extrude(0.75)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.7578947368421053)\nloop1=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.4736842105263158)\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.515625)\nsolid=solid0",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.7578947368421053)\nloop1=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.4578947368421053)\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.375)\nsolid=solid0\n"
    },
    {
        "predicted_code": "# generated by caffe2.pythontools.generator\nimport cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.7578947368421053)\nloop1=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.125)\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.3125)\nsolid=solid0",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, 0.0), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.7421052631578947)\nloop1=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.09473684210526316)\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.3515625)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, 0.0), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.7578947368421053)\nsolid0=wp_sketch0.add(loop0).extrude(0.75)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 =",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.7578947368421053, 0.0).circle(0.7578947368421053)\nsolid0=wp_sketch0.add(loop0).extrude(0.453125)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0234375, -0.015625, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.0, 0.0).threePointArc((-0.026414473684210524, -0.017737313527390387), (0.016484375, 0.02388157894736842)).threePointArc((0.02618421052631579, 0.031276315789473684), (0.01684210526",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.0, 0.0234375), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\nloop0=wp_sketch0.moveTo(0.0, 0.0).threePointArc((0.0008558886926831073, -0.009999895744201938), (0.003289473684210526, -0.019736842105263157)).lineTo(0.003289473684210526, -0.0390625).lineTo(0.005756578947368421, -0.0390625).lineTo(0.005756578947368421, -0.018914473684210526).threePointArc((0.0032974335618645503, -0.009598873110522415), (0.0024671052631578946, 0.0)).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.75)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(0.75, 0.0, 0.0234375), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\nloop1=wp_sketch1.moveTo(0.0, 0.0).threePointArc((0.000643017198702741, -0.007925809014733722), (0.002631578947368421, -0.015625)).lineTo(0.002631578947368421, 0.0).lineTo(0.0, 0.0).close()\nsolid1=wp_sketch1.add(loop1).extrude(-0.75)\nsolid=solid.union(solid1)\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, -0.265625, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.75, 0.0).lineTo(0.75, 0.23421052631578947).lineTo(0.0, 0.23421052631578947).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.0234375)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(0.0, -0.265625, 0.",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, -0.4296875, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.0, 0.0).threePointArc((0.023123148853693615, -0.05582421956735902), (0.07894736842105263, -0.07894736842105263)).lineTo(1.4210526315789473, -0.07894736842105263).threePointArc((1.4768768511463064, -0.05582421956735902), (1.5, 0.0)).lineTo(1.5, 0.868421052631579).threePointArc((1.4768768511463064, 0.924245272198938), (1.4210526315789473, 0.9473684210526316)).lineTo(0.07894736842105263, 0.9473684210526316).threePointArc((0.023123148853693615, 0.924245272198938), (0.0, 0.868421052631579)).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.234375)\nsolid=solid0\n"
    },
    {
        "predicted_code": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.078125, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.07894736842105263, 0.0).circle(0.07894736842105263)\nloop1=wp_sketch0.moveTo(0.07894736842105263, 0.0).circle(0.039473684210526314)\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.75)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.",
        "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.03125, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.035526315789473684, 0.0).circle(0.034786184210526316)\nloop1=wp_sketch0.moveTo(0.035526315789473684, 0.0).circle(0.011842105263157895)\nsolid0=wp_sketch0.add(loop0).add(loop1).extrude(0.75)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(-0.015625, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop2=wp_sketch1.moveTo(0.011842105263157895, 0.0).circle(0.011842105263157895)\nsolid1=wp_sketch1.add(loop2).extrude(0.75)\nsolid=solid.union(solid1)\n"
    }
]